### ISSUE TITLE
ClassNotFoundException: org.codenarc.rule. gosu.GosuClassSizeRule

### ISSUE THREAD

**Issue by wombatojad** [enoviti/sonar-gosu#1]
I am trying to use your sonar-gosu plugin and I am having some difficulties.
I performed installation according to manual and this is my sonar-project.properties:

sonar.projectKey=org.sonarqube:java-ut-it-jacoco-sq-scanner
sonar.projectName=Java :: UT + IT Jacoco :: SonarQube Scanner
sonar.projectVersion=1.0
 
sonar.tests=gtest
sonar.sources=gsrc

#Tells SonarQube where the unit tests execution reports are
sonar.junit.reportsPath=reports/junit

#Tells SonarQube where the unit tests code coverage report is
sonar.jacoco.reportPath=reports/jacoco/jacoco-ut.exec

#Tells SonarQube where the integration tests code coverage report is
sonar.jacoco.itReportPath=reports/jacoco/jacoco-it.exec

# Encoding of the source files
sonar.sourceEncoding=UTF-8

When I run sonar-scanner i receive:
ERROR: Error during SonarQube Scanner execution
java.lang.RuntimeException: java.lang.ClassNotFoundException: org.codenarc.rule.
gosu.GosuClassSizeRule
        at com.google.common.base.Throwables.propagate(Throwables.java:160)
        at org.sonar.core.platform.PicoUtils.propagate(PicoUtils.java:45)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentC
ontainer.java:145)

**Comment by ggaarryyyy93** [comment]
I ran into the same issue.  Did you end up figuring it out?

**Comment by Elnazmirrahimi** [comment]
I have download the sonar gosu from git hub, can you mention the step you follow to install it

**Comment by circa10a** [comment]
I am getting same error as @wombatojad above. Any advice @anshumanpurohit ?

**Comment by ArronaxKP** [comment]
Anyone have any update or workaround for this?

**Comment by caiohcl** [comment]
I've been facing the same issue. Does anyone have an update about this?

**Comment by AnjaneyalnDatla** [comment]
Same issue here. Did this work for anybody

**Comment by circa10a** [comment]
Nope. This is a dead end

**Comment by ArronaxKP** [comment]
Yes. After quite a bit of digging this plugin is sorely unfinished. I know of someone developing a plugin from the ground up. If I ever get a copy I will share the GitHub link

**Comment by circa10a** [comment]
Please do!
Thanks!

**Comment by circa10a** [comment]
@killerwizz1 any updates?

**Comment by ArronaxKP** [comment]
So I can confirm they built a working "prototype" but they never really integrated any real rules.
Only rules was length line overflow and Class name capitalized first line. 
Is this something worth sharing. It was no use for my use case

**Comment by westwoodad** [comment]
Thanks for the update @killerwizz1 , I think unless Guidewire or Sonar get involved in creating this then it is unlikely to ever get off the ground. I have been pushing Sonar to create a plugin for GoSu, surely the ROI would be quick because of the big players that use Guidewire and the amount of code that would be scanned. But they don't appear to be prioritising this at the moment.

I have created this today, if anyone is interested in voting? -
https://community.sonarsource.com/t/add-support-for-gosu-language/7933

**Comment by anshumanpurohit** [comment]
I created the project for a specific version of sonar. But haven’t been getting time to upgrade. If you’re inclined to send me a PR I’ll merge it.

________________________________

**Comment by ArronaxKP** [comment]
If you want a SonarQube plugin for Guidewire then speak to Guidewire. They actually have an accelerator already created for GW9+. It works on Sonarqube LTS.

**Comment by westwoodad** [comment]
To be honest I don't care who writes it...but as Sonar will potentially benefit the most from new language support of GoSu, I would expect them to do the development to start with...or maybe they could collaborate with Guidewire?

I'll have a look at the accelerator in the meantime though, thanks for that info,

**Comment by anshumanpurohit** [comment]
This is not sponsored project. OSS like this relies on developers contributions. @circa10a can attest this as he's the only one who has contributed OSS communities including this one. 

So, I would ask again. Contribute a PR or don't demand support for something you got for free!

**Comment by westwoodad** [comment]
@anshumanpurohit 
Just to be clear, I have not asked you guys for anything...read my comments. I have said that as GoSu is a proprietary language then perhaps Guidewire should look to offer support, they created it, but the main beneficiaries would be Sonar, so perhaps the should invest too. We pay a licence fee for Sonar and we are asking them for support. I posted it here because I thought it would be of interest.

If you want to show me where I have 'demanded support' from you guys then I will look at that and apologise, until then all I am doing is trying to share information with you. Obviously I will stop now, as it seems to be causing offence, although I have no idea why.

Thanks again to @killerwizz1 though, in the spirit of sharing information, I now know about an accelerator that might help us....that was written by Guidewire.

**Comment by abhijay94** [comment]
@anshumanpurohit Can you please let me know the exact version of SonarCube and SonarScanner this plugin was developed for? I'm currently running it on SonarCube 5.6.7(previous LTS) along with SonarScanner 3.3 and getting this exact error. Not sure what's wrong as the `org.sonar.api.profiles.RulesProfile` was marked  `@deprecated` and not removed until version 7.6. I'm interested in upgrading this plugin to the latest version of SonarCube but first I need to see if it works for at least one of the older versions. This would greatly help in estimating the effort needed for the same. Really appreciate you making this repo Open Source.
Thanks

**Comment by anshumanpurohit** [comment]
@abhijay94 This project is abandoned in favor of GW managed Accelerator. Please use SonarQube plug-in  from Guidewire's Marketplace instead. Let me know if there is any reason you will not be able to use that and we'd like to maintain this project. Thanks for your interest.
